# Generated by Django 4.1.3 on 2023-01-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maint',
            name='svc',
        ),
        migrations.AddField(
            model_name='maint',
            name='service',
            field=models.CharField(choices=[('W', 'Wash'), ('T', 'Tires'), ('O', 'Oil')], default='W', max_length=1, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='maint',
            name='date',
            field=models.DateField(verbose_name='Date of Service'),
        ),
    ]
