# Generated by Django 4.1.3 on 2023-01-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_maint_svc_maint_service_alter_maint_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maint',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='maint',
            name='service',
            field=models.CharField(choices=[('W', 'Wash'), ('T', 'Tires'), ('O', 'Oil')], default='W', max_length=1),
        ),
    ]
