# Generated by Django 4.1.3 on 2023-01-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_part_car_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='purpose',
            field=models.CharField(max_length=20, verbose_name='Purpose (Interior or Exterior)'),
        ),
    ]
